### ISSUE TITLE
Running errors caused by different versions of ROS

### ISSUE THREAD

**Issue by BIT-DYN** [SamsungLabs/HIO-SDF#1]
Hello, thank you for the fantastic work on open source!

I encountered the following issue while running. 

Since my Ubuntu version is 18.04, it does not support Python 3, and the version of ros is melodic.

Although I successfully compiled, I faced a problem during roslaunch:

> (pyvenv) dyn@auto:~/SDF/hio_ws$ roslaunch hio_sdf dataset_adapter.launch
Traceback (most recent call last):
  File "/opt/ros/melodic/bin/roslaunch", line 34, in <module>
    import roslaunch
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/__init__.py", line 52, in <module>
    from . import param_dump as roslaunch_param_dump
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/param_dump.py", line 40, in <module>
    import roslaunch.config
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/config.py", line 45, in <module>
    import rospkg.distro
  File "/usr/lib/python2.7/dist-packages/rospkg/distro.py", line 44, in <module>
    import yaml
  File "/home/dyn/SDF/hio_ws/pyvenv/lib/python3.6/site-packages/yaml/__init__.py", line 362
    class YAMLObject(metaclass=YAMLObjectMetaclass):
                              ^
SyntaxError: invalid 

Do you have any suggestions?

**Comment by vvasilo** [comment]
Thank you for your interest in HIO-SDF! We are sorry for the inconvenience but unfortunately, this package has not been tested with Python 2 or ROS Melodic. I would suggest upgrading to Python 3 and ROS Noetic to ensure compatibility.
